### ISSUE TITLE
Bug: Minor fix with Github issues badges

### ISSUE THREAD

**Issue by astrochun** [UAL-RE/redata-docs#13]
For badges that lists the status of repositories issues (open/close) via Shields.io badges, the query will need: `is:issue`. Otherwise this will include open/merged PRs.

**Comment by astrochun** [comment]
I'm assigning this to @yhan818 as this is a small issue to use for on-boarding.

**Comment by yhan818** [comment]
Fixed this issue.

**Comment by zoidy** [comment]
Fixed in #26
