### ISSUE TITLE
Add RTDs page for ReQUIAM

### ISSUE THREAD

**Issue by astrochun** [UAL-RE/redata-docs#16]
The RTDs page is now live at https://requiam.readthedocs.io.

A simple update to `source/repos.rst` is needed.
﻿

**Comment by zoidy** [comment]
@yhan818 , I think you merged the PR and closed this issue a bit prematurely. As I mentioned in my review, the change you made might break the references. Indeed, that seems to have happened. Therefore, I'm re-opening this issue.

![image](https://user-images.githubusercontent.com/7082025/167496117-5fdbbc90-3111-498d-8a1f-0d9a5a639bd8.png)

**Comment by yhan818** [comment]
Thanks for checking. While the updated one is good, the README/changelog do not go to the right ones. I will check tonight and hopefully fix them asap.

**Comment by yhan818** [comment]
Before I figure out what went wrong, I rolled back to the stable version on RTD.

**Comment by yhan818** [comment]
I found out what went wrong. It was an additional anchor (ReQuiam README) which should be removed.
